server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://101.200.78.91:3306/post_calendar?serverTimezone=GMT%2B8&useSSL=true
    username: postAdmin
    password: 30933847683279925
    hikari:
      max-lifetime: 180000
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: top.rrricardo.postcalendarbackend.models
user:
  password-salt: cvmnasdvnjcnvkmdfvhldfckvndvmbnklsdfgnvjkxc
  rootUserEmailAddress: root@root.org
  rootUsername: root
  rootPassword: root
  jwt:
    secret: ascnkuxvmnwerkjvfxckvnkujsefnvxcvsdfjkxcvjnksdjnxcvjnsd
    lifetime: 7
    issuer: PostCalendarBackend
group:
  usersName: users
  usersDetails: Group for all users


