name: Run Maven Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-23.04:host
    steps:
      - name: Checkout
        uses: https://git.rrricardo.top/actions/checkout@v3
      - run: ./mvnw clean
      - run: ./mvnw test